[PDP] Make template notebooks (trying again)
datakind/student-success-tool pull request #26
Opened 2024-11-09 20:49 UTC by bdewilde

## changes

## context

## questions

2024-11-16 17:01 UTC, kaylawilding requested changes

2024-11-16 17:12 UTC, bdewilde commented on notebooks/pdp/01-data-assessment-eda-TEMPLATE.py
> +schema = "SCHOOL_bronze"
Yup, I did something like this in USCB. This notebook is just a draft, I was hoping you'd be updating it, but I can extend what I have further given recent experience if you'd like.

2024-11-16 17:13 UTC, kaylawilding commented on notebooks/pdp/01-data-assessment-eda-TEMPLATE.py
> +schema = "SCHOOL_bronze"
Oh cool, yes I can update it totally, you can ignore my comments if you want and just merge and I can update it all!

2024-11-16 17:15 UTC, bdewilde commented on notebooks/pdp/01-data-assessment-eda-TEMPLATE.py
> +print(f"rows x cols = {df_course_raw.shape}")
Uniqueness checks are embedded within the raw data schemas -- this gets flagged automatically when validating the data 👍

2024-11-16 17:16 UTC, bdewilde commented on notebooks/pdp/01-data-assessment-eda-TEMPLATE.py
> +df_course
This is just a template -- all are free to customize as they prefer! :)

2024-11-23 18:23 UTC, bdewilde commented on notebooks/pdp/01-data-assessment-eda-TEMPLATE.py
> +_ = msno.matrix(
Sorry, but I fully don't understand this comment. Why would variable names be changing? And why would that matter here?

2024-11-29 17:50 UTC, bdewilde commented
Hey, I'm trying to do a v0.1 release of this package, and I'd strongly prefer to have template notebooks included. So, I'm going to merge this in, but let's plan to iterate on them for a follow-up release.

2024-11-29 17:50 UTC, merged

2024-11-29 18:10 UTC, Eyong20 reviewed
reviewed