[pdp] Update template modeling nb to work
datakind/student-success-tool pull request #46
Opened 2024-12-29 20:01 UTC by bdewilde

## changes

## context

## questions

2025-01-02 23:23 UTC, vishpillai123 requested changes
The code looks relatively similar to what we have in our private repo, though I'm having some trouble running the notebook without a config.toml file. I was wondering if we're expected to create the config file from scratch?

2025-01-02 23:23 UTC, vishpillai123 commented on notebooks/pdp/03-train-evaluate-model-TEMPLATE.py
> +config = configs.load_config("./config.toml", schema=configs.PDPProjectConfig)
should we put a sample .toml file for reference? 

I'm not seeing one pushed in the parent repo, so this errored out for me.

2025-01-03 00:29 UTC, bdewilde commented on notebooks/pdp/03-train-evaluate-model-TEMPLATE.py
> +config = configs.load_config("./config.toml", schema=configs.PDPProjectConfig)
Well, these templates aren't meant to be runnable as-is -- they're meant to be copied into school-specific contexts where they are then runnable :) The idea of a sample project config seems useful, but I'd consider it out of scope for the changes here!

2025-01-03 00:45 UTC, bdewilde commented on notebooks/pdp/03-train-evaluate-model-TEMPLATE.py
> +config = configs.load_config("./config.toml", schema=configs.PDPProjectConfig)
(I'll see about adding one in a separate PR)

2025-01-03 16:30 UTC, vishpillai123 approved these changes

2025-01-04 17:39 UTC, merged

2025-01-04 19:23 UTC, bdewilde commented on notebooks/pdp/03-train-evaluate-model-TEMPLATE.py
> +config = configs.load_config("./config.toml", schema=configs.PDPProjectConfig)
https://github.com/datakind/student-success-tool/pull/50